zend_extension=/opt/zentao/php/lib/ioncube/ioncube_loader_lin_8.4_ts.so

expose_php=Off
display_errors=Off
log_errors=On
error_log=/opt/zentao/logs/php-error.log
memory_limit=256M
max_execution_time=120
post_max_size=64M
upload_max_filesize=64M
date.timezone=Asia/Shanghai
